import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, Printer } from "lucide-react";

interface MonthlyReportCardProps {
  month: number;
  year: number;
  summary: string;
  reportData: {
    expenses: {
      totalExpenses: number;
      topExpenseCategory: string;
      topExpenseAmount: number;
      categoryBreakdown: Record<string, number>;
    };
    teachers: {
      totalTeachers: number;
      averagePerformance: number;
      averageAttendance: number;
      topPerformers: Array<{ name: string; rating: number }>;
      needsImprovement: Array<{ name: string; rating: number }>;
    };
    employees: {
      totalEmployees: number;
      averagePerformance: number;
      averageAttendance: number;
      departmentBreakdown: Record<string, number>;
    };
    classes: { total: number };
  };
}

export default function MonthlyReportCard({ month, year, summary, reportData }: MonthlyReportCardProps) {
  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const reportContent = `
MONTHLY SCHOOL MANAGEMENT REPORT
${monthNames[month - 1]} ${year}

EXECUTIVE SUMMARY
${summary}

FINANCIAL SUMMARY
Total Expenses: RM ${reportData.expenses.totalExpenses.toFixed(2)}
Top Expense Category: ${reportData.expenses.topExpenseCategory} (RM ${reportData.expenses.topExpenseAmount.toFixed(2)})

Expense Breakdown:
${Object.entries(reportData.expenses.categoryBreakdown)
  .map(([category, amount]) => `  - ${category}: RM ${(amount as number).toFixed(2)}`)
  .join("\n")}

TEACHER PERFORMANCE
Total Teachers: ${reportData.teachers.totalTeachers}
Average Performance Rating: ${reportData.teachers.averagePerformance}/5.0
Average Attendance: ${reportData.teachers.averageAttendance}%

Top Performers:
${reportData.teachers.topPerformers.map(t => `  - ${t.name}: ${t.rating}/5.0`).join("\n")}

Needs Improvement:
${reportData.teachers.needsImprovement.length > 0 ? reportData.teachers.needsImprovement.map(t => `  - ${t.name}: ${t.rating}/5.0`).join("\n") : "  - None"}

EMPLOYEE MANAGEMENT
Total Employees: ${reportData.employees.totalEmployees}
Average Performance Rating: ${reportData.employees.averagePerformance}/5.0
Average Attendance: ${reportData.employees.averageAttendance}%

Department Breakdown:
${Object.entries(reportData.employees.departmentBreakdown)
  .map(([dept, count]) => `  - ${dept}: ${count}`)
  .join("\n")}

CLASSES
Total Classes: ${reportData.classes.total}

Generated: ${new Date().toLocaleString()}
    `;

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Monthly-Report-${month}-${year}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <Card className="w-full bg-gradient-to-br from-blue-50 to-indigo-50 border-indigo-200">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-2xl text-indigo-900">
              {monthNames[month - 1]} {year} Report
            </CardTitle>
            <CardDescription>Generated by Amira AI Assistant</CardDescription>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handlePrint}
              className="gap-2"
            >
              <Printer className="w-4 h-4" />
              Print
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownload}
              className="gap-2"
            >
              <Download className="w-4 h-4" />
              Download
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Executive Summary */}
        <div className="bg-white rounded-lg p-4 border border-indigo-100">
          <h3 className="font-semibold text-indigo-900 mb-2">Executive Summary</h3>
          <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">{summary}</p>
        </div>

        {/* Key Metrics Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="bg-white rounded-lg p-4 border border-indigo-100">
            <div className="text-xs font-semibold text-gray-600 uppercase">Total Expenses</div>
            <div className="text-2xl font-bold text-indigo-600 mt-2">
              RM {reportData.expenses.totalExpenses.toFixed(2)}
            </div>
          </div>
          <div className="bg-white rounded-lg p-4 border border-indigo-100">
            <div className="text-xs font-semibold text-gray-600 uppercase">Teachers</div>
            <div className="text-2xl font-bold text-indigo-600 mt-2">
              {reportData.teachers.totalTeachers}
            </div>
            <div className="text-xs text-gray-600 mt-1">
              Avg: {reportData.teachers.averagePerformance}/5.0
            </div>
          </div>
          <div className="bg-white rounded-lg p-4 border border-indigo-100">
            <div className="text-xs font-semibold text-gray-600 uppercase">Employees</div>
            <div className="text-2xl font-bold text-indigo-600 mt-2">
              {reportData.employees.totalEmployees}
            </div>
            <div className="text-xs text-gray-600 mt-1">
              Avg: {reportData.employees.averagePerformance}/5.0
            </div>
          </div>
          <div className="bg-white rounded-lg p-4 border border-indigo-100">
            <div className="text-xs font-semibold text-gray-600 uppercase">Classes</div>
            <div className="text-2xl font-bold text-indigo-600 mt-2">
              {reportData.classes.total}
            </div>
          </div>
        </div>

        {/* Top Expense Category */}
        <div className="bg-white rounded-lg p-4 border border-indigo-100">
          <h3 className="font-semibold text-indigo-900 mb-3">Top Expense Category</h3>
          <div className="flex items-center justify-between">
            <Badge variant="outline" className="text-base px-3 py-1">
              {reportData.expenses.topExpenseCategory}
            </Badge>
            <span className="text-lg font-bold text-indigo-600">
              RM {reportData.expenses.topExpenseAmount.toFixed(2)}
            </span>
          </div>
        </div>

        {/* Top Teachers */}
        {reportData.teachers.topPerformers.length > 0 && (
          <div className="bg-white rounded-lg p-4 border border-indigo-100">
            <h3 className="font-semibold text-indigo-900 mb-3">Top Performing Teachers</h3>
            <div className="space-y-2">
              {reportData.teachers.topPerformers.map((teacher, idx) => (
                <div key={idx} className="flex items-center justify-between">
                  <span className="text-sm text-gray-700">{teacher.name}</span>
                  <Badge variant="secondary">{teacher.rating}/5.0</Badge>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Needs Improvement */}
        {reportData.teachers.needsImprovement.length > 0 && (
          <div className="bg-white rounded-lg p-4 border border-orange-200 bg-orange-50">
            <h3 className="font-semibold text-orange-900 mb-3">Teachers Needing Support</h3>
            <div className="space-y-2">
              {reportData.teachers.needsImprovement.map((teacher, idx) => (
                <div key={idx} className="flex items-center justify-between">
                  <span className="text-sm text-gray-700">{teacher.name}</span>
                  <Badge variant="destructive">{teacher.rating}/5.0</Badge>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Department Breakdown */}
        <div className="bg-white rounded-lg p-4 border border-indigo-100">
          <h3 className="font-semibold text-indigo-900 mb-3">Department Breakdown</h3>
          <div className="grid grid-cols-2 gap-3">
            {Object.entries(reportData.employees.departmentBreakdown).map(([dept, count]) => (
              <div key={dept} className="flex items-center justify-between p-2 bg-indigo-50 rounded">
                <span className="text-sm text-gray-700">{dept}</span>
                <Badge>{count}</Badge>
              </div>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
